### ISSUE TITLE
落地点出现偏移，不是正中心

### ISSUE THREAD

**Issue by suoak** [experdot/AutoJump.NET#2]
程序运行后，落地点出现偏移，不是正中心，这个是什么原因

**Comment by experdot** [comment]
@suoak 识别是正确的吗？目前一部分特殊的盒子不能够识别正中心。如果识别是正确的，实际的落点有偏差，那么需要你手动调节系数：[点击查看代码](https://github.com/experdot/AutoJump.NET/blob/master/AutoJump.Robot.Simple/Robot/SimpleRobot.vb#L62)
